### ISSUE TITLE
TypeError: mathutils.Vector()

### ISSUE THREAD

**Issue by carter2422** [CGCookie/retopoflow#109]
As reported by [Miguel Salinas](https://cgcookiemarkets.com/blender/forums/topic/error-working-with-large-geometry/), activating Polystrips when viewing from certain angles on the attached model causes an instant crash. 

```
Traceback (most recent call last):
  File "/Users/jonathanwilliamson/Dropbox (Personal)/blenderDev/addons/cgCookie/scripts/addons/retopoFlow/__init__.py", line 2192, in modal
    ret = self.ui.modal(context, event)
  File "/Users/jonathanwilliamson/Dropbox (Personal)/blenderDev/addons/cgCookie/scripts/addons/retopoFlow/__init__.py", line 4033, in modal
    nmode = FSM[self.mode](eventd)
  File "/Users/jonathanwilliamson/Dropbox (Personal)/blenderDev/addons/cgCookie/scripts/addons/retopoFlow/__init__.py", line 3129, in modal_main
    self.hover_geom(eventd)
  File "/Users/jonathanwilliamson/Dropbox (Personal)/blenderDev/addons/cgCookie/scripts/addons/retopoFlow/__init__.py", line 2877, in hover_geom
    inside = contour_utilities.point_inside_loop2d([c0,c1,c2,c3],Vector((mx,my)))
  File "/Users/jonathanwilliamson/Dropbox (Personal)/blenderDev/addons/cgCookie/scripts/addons/retopoFlow/contour_utilities.py", line 728, in point_inside_loop2d
    loop[i] = Vector(loop[i])
TypeError: mathutils.Vector()
```

**Blend File**: https://www.dropbox.com/s/ku30t8y9y4guklt/chick41_blendswap.blend?dl=0

**Comment by vxlcoder** [comment]
is this still an issue?  i cannot download the linked .blend file to test

**Comment by carter2422** [comment]
I don't believe this is an issue anymore. Going to close for now.
