### ISSUE TITLE
Crash while exiting to wireframe view

### ISSUE THREAD

**Issue by jlampel** [CGCookie/retopoflow#1196]
If you start RetopoFlow while in wireframe view, it will crash upon exiting. This happens even in the default scene and no other actions. 

Log:
```
Read prefs: C:\Users\jonat\AppData\Roaming\Blender Foundation\Blender\3.4\config\userpref.blend
Addon Common: (shaders) GLSL Version: 4.50 NVIDIA
Addon Common: compiling UI shader
Addon Common: batching for shader
Addon Common: UI shader initialized
Addon Common: ########################################
              Loading shader using Shader
RetopoFlow: Initial load
RetopoFlow git: v3.3.0 df2e6dfa6f9222dcd3eb92e2844bcbf71cccafc4
gpustate.gpu_info cannot get shader version!
RetopoFlow options path: C:\Users\jonat\Documents\GitHub\retopoflow\RetopoFlow_options.json
Addon Common: (bmesh_render) GLSL Version: NVIDIA Corporation, NVIDIA GeForce RTX 3060/PCIe/SSE2, 4.5.0 NVIDIA 528.24, (no shader version)
cgcookie addon: Verbose is enabled
cgcookie addon: Read in JSON settings from file
WARN (bpy.rna): C:\Users\blender\git\blender-v340\blender.git\source\blender\python\intern\bpy_rna.c:1341 pyrna_enum_to_py: current value '5' matches no enum in 'View3DShading', '(null)', 'studio_light'
RetopoFlow keymaps path: C:\Users\jonat\Documents\GitHub\retopoflow\RetopoFlow_keymaps.json
RetopoFlow: storing clip distances: 0.10000000149011612 1000.0
RetopoFlow: storing view: <Vector (-0.0859, 0.0996, 0.4287)> 4.313713550567627
RetopoFlow: computing unit scaling factor
  Unit scaling factor: 10.0
RetopoFlow: scaling to unit box
RetopoFlow: scaling to factor=10.0, view='SCALE', clip='OVERRIDE', mesh='SCALE'
RetopoFlow: Pausing help image preloading (1678325839.317598)
ERROR 1/10 (UI_Document.draw: start): invalid enum
  File "C:\Users\jonat\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\retopoflow\addon_common\cookiecutter\cookiecutter_ui.py", line 117, in postpixel
    try: self.document.draw(self.context)
  File "C:\Users\jonat\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\retopoflow\addon_common\common\ui_document.py", line 688, in draw
    Globals.drawing.glCheckError('UI_Document.draw: start')
  File "C:\Users\jonat\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\retopoflow\addon_common\common\decorators.py", line 217, in callit
    ret = fn(*args, **kwargs)
  File "C:\Users\jonat\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\retopoflow\addon_common\common\drawing.py", line 516, in glCheckError
    traceback.print_stack()
Addon Common: Loaded font id=25: C:\Users\jonat\Documents\GitHub\retopoflow\addon_common\common\fonts\DroidSans-Blender.ttf
RetopoFlow: Setting up target mesh (0.0010004043579101562)
RetopoFlow: Setting up source mesh(es) (0.0009999275207519531)
ERROR 2/10 (UI_Document.draw: start): invalid enum
  File "C:\Users\jonat\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\retopoflow\addon_common\cookiecutter\cookiecutter_ui.py", line 117, in postpixel
    try: self.document.draw(self.context)
  File "C:\Users\jonat\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\retopoflow\addon_common\common\ui_document.py", line 688, in draw
    Globals.drawing.glCheckError('UI_Document.draw: start')
  File "C:\Users\jonat\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\retopoflow\addon_common\common\decorators.py", line 217, in callit
    ret = fn(*args, **kwargs)
  File "C:\Users\jonat\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\retopoflow\addon_common\common\drawing.py", line 516, in glCheckError
    traceback.print_stack()
  rfsources...
  bboxes...
  drawing...
  done!
RetopoFlow: Setting up symmetry data structures (0.0015211105346679688)
ERROR 3/10 (UI_Document.draw: start): invalid enum
  File "C:\Users\jonat\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\retopoflow\addon_common\cookiecutter\cookiecutter_ui.py", line 117, in postpixel
    try: self.document.draw(self.context)
  File "C:\Users\jonat\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\retopoflow\addon_common\common\ui_document.py", line 688, in draw
    Globals.drawing.glCheckError('UI_Document.draw: start')
  File "C:\Users\jonat\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\retopoflow\addon_common\common\decorators.py", line 217, in callit
    ret = fn(*args, **kwargs)
  File "C:\Users\jonat\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\retopoflow\addon_common\common\drawing.py", line 516, in glCheckError
    traceback.print_stack()
RetopoFlow: Setting up rotation target (0.0010001659393310547)
ERROR 4/10 (UI_Document.draw: start): invalid enum
  File "C:\Users\jonat\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\retopoflow\addon_common\cookiecutter\cookiecutter_ui.py", line 117, in postpixel
    try: self.document.draw(self.context)
  File "C:\Users\jonat\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\retopoflow\addon_common\common\ui_document.py", line 688, in draw
    Globals.drawing.glCheckError('UI_Document.draw: start')
  File "C:\Users\jonat\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\retopoflow\addon_common\common\decorators.py", line 217, in callit
    ret = fn(*args, **kwargs)
  File "C:\Users\jonat\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\retopoflow\addon_common\common\drawing.py", line 516, in glCheckError
    traceback.print_stack()
RetopoFlow: Setting up RetopoFlow states (0.045009613037109375)
ERROR 5/10 (UI_Document.draw: start): invalid enum
  File "C:\Users\jonat\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\retopoflow\addon_common\cookiecutter\cookiecutter_ui.py", line 117, in postpixel
    try: self.document.draw(self.context)
  File "C:\Users\jonat\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\retopoflow\addon_common\common\ui_document.py", line 688, in draw
    Globals.drawing.glCheckError('UI_Document.draw: start')
  File "C:\Users\jonat\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\retopoflow\addon_common\common\decorators.py", line 217, in callit
    ret = fn(*args, **kwargs)
  File "C:\Users\jonat\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\retopoflow\addon_common\common\drawing.py", line 516, in glCheckError
    traceback.print_stack()
ERROR 6/10 (UI_Document.draw: start): invalid enum
  File "C:\Users\jonat\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\retopoflow\addon_common\cookiecutter\cookiecutter_ui.py", line 117, in postpixel
    try: self.document.draw(self.context)
  File "C:\Users\jonat\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\retopoflow\addon_common\common\ui_document.py", line 688, in draw
    Globals.drawing.glCheckError('UI_Document.draw: start')
  File "C:\Users\jonat\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\retopoflow\addon_common\common\decorators.py", line 217, in callit
    ret = fn(*args, **kwargs)
  File "C:\Users\jonat\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\retopoflow\addon_common\common\drawing.py", line 516, in glCheckError
    traceback.print_stack()
RetopoFlow: Setting up RetopoFlow tools (0.009002208709716797)
ERROR 7/10 (UI_Document.draw: start): invalid enum
  File "C:\Users\jonat\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\retopoflow\addon_common\cookiecutter\cookiecutter_ui.py", line 117, in postpixel
    try: self.document.draw(self.context)
  File "C:\Users\jonat\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\retopoflow\addon_common\common\ui_document.py", line 688, in draw
    Globals.drawing.glCheckError('UI_Document.draw: start')
  File "C:\Users\jonat\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\retopoflow\addon_common\common\decorators.py", line 217, in callit
    ret = fn(*args, **kwargs)
  File "C:\Users\jonat\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\retopoflow\addon_common\common\drawing.py", line 516, in glCheckError
    traceback.print_stack()
RetopoFlow: Setting up grease marks (0.0009999275207519531)
ERROR 8/10 (UI_Document.draw: start): invalid enum
  File "C:\Users\jonat\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\retopoflow\addon_common\cookiecutter\cookiecutter_ui.py", line 117, in postpixel
    try: self.document.draw(self.context)
  File "C:\Users\jonat\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\retopoflow\addon_common\common\ui_document.py", line 688, in draw
    Globals.drawing.glCheckError('UI_Document.draw: start')
  File "C:\Users\jonat\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\retopoflow\addon_common\common\decorators.py", line 217, in callit
    ret = fn(*args, **kwargs)
  File "C:\Users\jonat\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\retopoflow\addon_common\common\drawing.py", line 516, in glCheckError
    traceback.print_stack()
ERROR 9/10 (UI_Document.draw: start): invalid enum
  File "C:\Users\jonat\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\retopoflow\addon_common\cookiecutter\cookiecutter_ui.py", line 117, in postpixel
    try: self.document.draw(self.context)
  File "C:\Users\jonat\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\retopoflow\addon_common\common\ui_document.py", line 688, in draw
    Globals.drawing.glCheckError('UI_Document.draw: start')
  File "C:\Users\jonat\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\retopoflow\addon_common\common\decorators.py", line 217, in callit
    ret = fn(*args, **kwargs)
  File "C:\Users\jonat\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\retopoflow\addon_common\common\drawing.py", line 516, in glCheckError
    traceback.print_stack()
RetopoFlow: Setting up visualizations (0.01000213623046875)
ERROR 10/10 (UI_Document.draw: start): invalid enum
  File "C:\Users\jonat\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\retopoflow\addon_common\cookiecutter\cookiecutter_ui.py", line 117, in postpixel
    try: self.document.draw(self.context)
  File "C:\Users\jonat\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\retopoflow\addon_common\common\ui_document.py", line 688, in draw
    Globals.drawing.glCheckError('UI_Document.draw: start')
  File "C:\Users\jonat\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\retopoflow\addon_common\common\decorators.py", line 217, in callit
    ret = fn(*args, **kwargs)
  File "C:\Users\jonat\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\retopoflow\addon_common\common\drawing.py", line 516, in glCheckError
    traceback.print_stack()
RetopoFlow: Setting up user interface (0.012003421783447266)
RetopoFlow: Setting up undo system (0.0010004043579101562)
RetopoFlow: Checking auto save / save (0.0010001659393310547)
RetopoFlow: Checking target symmetry (0.017003774642944336)
RetopoFlow: Loading welcome message (0.016003847122192383)
RetopoFlow: Resuming help image preloading (0.01600360870361328)
RetopoFlow: done with start
RetopoFlow: unscaling from unit box
RetopoFlow: scaling to factor=1.0, view='RESTORE', clip='RESTORE', mesh='RESTORE'
RetopoFlow: unscaling from unit box
RetopoFlow: scaling to factor=1.0, view='RESTORE', clip='RESTORE', mesh='RESTORE'
CookieCutter_Exceptions: handling caught exception
    action: call end() with commit
____________________________________________________________________________________________________
Exception Info
- Time: 2023-03-08 17:37:25.021007
- Count: 1
- Hash: 469112d35603f4ce249274045a49429b
- Info:
  - EXCEPTION (<class 'TypeError'>): bpy_struct: item.attr = val: enum "" not found in ()
  -     .../cookiecutter\cookiecutter_blender.py
  - 000 0187:shading_matcap_set() def shading_matcap_set(self, v): self.context.space_data.shading.studio_light = v
  - 001 0049:restore() fn_set(self._storage[k])
  - 002 0055:restore_all() self.restore(k)
  - 003 0091:_cc_blenderui_end() self._storerestore.restore_all(ignore=ignore)
  -     C:\Users\jonat\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\retopoflow\retopoflow\rf\rf_ui.py
  - 004 0143:blender_ui_reset() self._cc_blenderui_end(ignore=({'panels'} if ignore_panels else None))
  -     C:\Users\jonat\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\retopoflow\retopoflow\retopoflow.py
  - 005 0142:end() self.blender_ui_reset()
  -     .../cookiecutter\cookiecutter_modal.py
  - 006 0164:modal_maindone() self.end()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
CookieCutter_Exceptions._callback_exception_callbacks: bpy_struct: item.attr = val: enum "" not found in ()
RF_UI.handle_exception: bpy_struct: item.attr = val: enum "" not found in ()
Info: Total files 11 | Changed 11 | Failed 0
Info: Saved "RetopoFlow_backup_EMERGENCY.blend"
Addon Common: Loaded font id=26: C:\Users\jonat\Documents\GitHub\retopoflow\addon_common\common\fonts\DejaVuSansMono.ttf
Traceback (most recent call last):
  File "C:\Users\jonat\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\retopoflow\addon_common\cookiecutter\cookiecutter_modal.py", line 57, in modal
    ret = fn_modal()
  File "C:\Users\jonat\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\retopoflow\addon_common\cookiecutter\cookiecutter_modal.py", line 120, in modal_mainloop
    self._cc_ui_end()
  File "C:\Users\jonat\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\retopoflow\addon_common\cookiecutter\cookiecutter_ui.py", line 137, in _cc_ui_end
    self._cc_blenderui_end()
  File "C:\Users\jonat\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\retopoflow\addon_common\cookiecutter\cookiecutter_blender.py", line 91, in _cc_blenderui_end
    self._storerestore.restore_all(ignore=ignore)
  File "C:\Users\jonat\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\retopoflow\addon_common\cookiecutter\cookiecutter_blender.py", line 55, in restore_all
    self.restore(k)
  File "C:\Users\jonat\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\retopoflow\addon_common\cookiecutter\cookiecutter_blender.py", line 49, in restore
    fn_set(self._storage[k])
  File "C:\Users\jonat\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\retopoflow\addon_common\cookiecutter\cookiecutter_blender.py", line 187, in shading_matcap_set
    def shading_matcap_set(self, v): self.context.space_data.shading.studio_light = v
TypeError: bpy_struct: item.attr = val: enum "" not found in ()
Error: Python: Traceback (most recent call last):
  File "C:\Users\jonat\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\retopoflow\addon_common\cookiecutter\cookiecutter_modal.py", line 57, in modal
    ret = fn_modal()
  File "C:\Users\jonat\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\retopoflow\addon_common\cookiecutter\cookiecutter_modal.py", line 120, in modal_mainloop
    self._cc_ui_end()
  File "C:\Users\jonat\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\retopoflow\addon_common\cookiecutter\cookiecutter_ui.py", line 137, in _cc_ui_end
    self._cc_blenderui_end()
  File "C:\Users\jonat\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\retopoflow\addon_common\cookiecutter\cookiecutter_blender.py", line 91, in _cc_blenderui_end
    self._storerestore.restore_all(ignore=ignore)
  File "C:\Users\jonat\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\retopoflow\addon_common\cookiecutter\cookiecutter_blender.py", line 55, in restore_all
    self.restore(k)
  File "C:\Users\jonat\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\retopoflow\addon_common\cookiecutter\cookiecutter_blender.py", line 49, in restore
    fn_set(self._storage[k])
  File "C:\Users\jonat\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\retopoflow\addon_common\cookiecutter\cookiecutter_blender.py", line 187, in shading_matcap_set
    def shading_matcap_set(self, v): self.context.space_data.shading.studio_light = v
TypeError: bpy_struct: item.attr = val: enum "" not found in ()

GitHub: Not reported, yet
```

**Comment by jlampel** [comment]
Fix confirmed!
