### ISSUE TITLE
[BUG] Retopoflow crashes, dissapears and scales mesh when making new mesh

### ISSUE THREAD

**Issue by VeronikaIsHere** [CGCookie/retopoflow#1317]
Retopoflow Version: *v3.4.3*

Blender Version/Hash: *4 and 4.1*

&nbsp;

**Issue:**

In a file where I have already used Retopoflow it is now not working anymore. Seems to be only in that file no matter the Blender version. When trying to make a new retopofow from from active or selection, Retopoflow crashes, dissapears from the UI and scales all visible meshes from originally ca. 30 cm to around 4 meter. Retopoflow is still in the Add Ons active. Turning it off and on doesn't change anything. Removing Retopoflow gives this error: 

_"Python: Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\python\Lib\shutil.py", line 622, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\python\Lib\shutil.py", line 620, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 32] Der Prozess kann nicht auf die Datei zugreifen, da sie von einem anderen Prozess verwendet wird: 'C:\\Users\\nika\\AppData\\Roaming\\BlenderFoundation\\Blender\\4.1\\scripts\\addons\\RetopoFlow\\addon_common\\common\\fonts\\DroidSans-Blender.ttf'"_

After closing Blender and opening it again it is back.

![image](https://github.com/CGCookie/retopoflow/assets/103097594/b11b1f74-356c-4d0c-abd1-5977d8b8c45c)
![image](https://github.com/CGCookie/retopoflow/assets/103097594/37473ce7-1404-4f23-b1c8-e2db39835168)
![image](https://github.com/CGCookie/retopoflow/assets/103097594/97fd6bfe-fe38-4015-bc5a-dce38aec5ce5)

&nbsp;

**How to Reproduce:**

- Selct highpoly mesh
- click sctive or cursor
- now Retopoflow crashes after showing "setting up target mesh" for a millisecond

**Comment by jlampel** [comment]
Hi, thank you for the report! Apologies that you never got a proper response. If you happen to still have the file, could you please share it so that we can test? Or if it has not happened since then in newer Retopoflow versions, we could close this out. It sounds like it could be related to #1127.

**Comment by jlampel** [comment]
I will close this out as we are focusing on Retopoflow 4 and this issue is quite old, but please feel free to re-open if it still is an issue in Retopoflow 3 and we will take a look at it.

**Comment by jlampel** [comment]
Actually this looks like the same issue as #1449 and we can continue the investigation there
