### ISSUE TITLE
[BUG] Error when enabling addon

### ISSUE THREAD

**Issue by windwardquasar** [CGCookie/retopoflow#1327]
Retopoflow Version: 3.4.3

Blender Version/Hash: 4.1.1

Platform Version/Distribution: GitHub

&nbsp;

**Issue:**
Add-on cannot be enabled. Console returns this error:
```
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\scripts\modules\addon_utils.py", line 376, in enable
    mod = importlib.import_module(module_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\python\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\cecil\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\RetopoFlow\__init__.py", line 48, in <module>
    from .addon_common.hive.hive import Hive
  File "C:\Users\cecil\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\RetopoFlow\addon_common\hive\hive.py", line 5, in <module>
    from ..common.blender import get_path_from_addon_root
  File "C:\Users\cecil\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\RetopoFlow\addon_common\common\__init__.py", line 59, in <module>
    from . import drawing as _
  File "C:\Users\cecil\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\RetopoFlow\addon_common\common\drawing.py", line 48, in <module>
    from .fontmanager import FontManager as fm
  File "C:\Users\cecil\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\RetopoFlow\addon_common\common\fontmanager.py", line 26, in <module>
    from . import gpustate
  File "C:\Users\cecil\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\RetopoFlow\addon_common\common\gpustate.py", line 904, in <module>
    print(f'Addon Common: {gpu_info()}')
                           ^^^^^^^^^^
  File "C:\Users\cecil\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\RetopoFlow\addon_common\common\decorators.py", line 286, in callit
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cecil\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\RetopoFlow\addon_common\common\gpustate.py", line 898, in gpu_info
    capabilities = {
                   ^
  File "C:\Users\cecil\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\RetopoFlow\addon_common\common\gpustate.py", line 899, in <dictcomp>
    a: fn() for (a, fn) in cap
       ^^^^
TypeError: function takes exactly 1 argument (0 given)

```

&nbsp;

**How to Reproduce:**
Click the enable add-on button. 

I was previously receiving an error log ending in "ModuleNotFoundError", I think it was similar to [this issue's log](https://github.com/CGCookie/retopoflow/issues/1301) (although I don't use Blender through Steam). I restarted Blender and now when I go to enable the add on I get the "TypeError" log that I pasted above. I've followed the instructions in the README.md file for when one is having difficulty enabling the add-on, but nothing changed. 

I've also re-installed Blender, which didn't help. Additionally, I tried downloading from the main GitHub page (not the releases) and I didn't have any trouble enabling the add-on that way, but I was getting the "invalid add-on folder name" thing. I've also only been trying to enable this in the default .blend file, if that helps narrow it down.

**Comment by vxlcoder** [comment]
thanks for the report, @windwardquasar. will take a look
