### ISSUE TITLE
[BUG] Strokes tool: unhandled exception on Ctrl+LMB

### ISSUE THREAD

**Issue by jfranmatheu** [CGCookie/retopoflow#1346]
Retopoflow Version: latest, v4.0.0 branch, hash=bf36eeaf6d12d4ae171c3740a92d71c5e82fdca5

Blender Version/Hash: 4.2.3 LTS, hash=0e22e4fcea03

Platform Version/Distribution: Windows 11, 10.0.22631

&nbsp;

**Issue:**

Unhandled exception in Stroke tool when Ctrl+Click. The consequent crash glitches the cursor graphic on screen, since it is not cleared afterwhile.

![image](https://github.com/user-attachments/assets/088335cd-fb6e-4185-a228-6ee56f822c13)

### Exception Traceback:

```cmd
RFCore_Operator.__init__
CACHING BVHS FOR ALL SOURCE OBJECTS
  0.00secs
RFCore_Operator executing
RFOperator.modal: Unhandled Exception Caught in self.update: BMVert.co
____________________________________________________________________________________________________
Exception Info
- Time: 2024-11-13 14:32:01.312271
- Count: 1
- Hash: 411c938379d6efc02f0a344c55e5beef
- Info:
  - EXCEPTION (<class 'TypeError'>): BMVert.co
  -     C:\Users\JF\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\retopoflow\retopoflow\rfoperators\transform.py
  - 000 0345:translate() bmv.co = co
  - 001 0310:update() self.translate(context, event)
  -     C:\Users\JF\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\retopoflow\retopoflow\common\operator.py
  - 002 0143:modal() ret = self.update(context, event)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RFOperator.modal: Unhandled Exception Caught in self.update: BMVert.co
____________________________________________________________________________________________________
Exception Info
- Time: 2024-11-13 14:32:16.100580
- Count: 2
- Hash: 411c938379d6efc02f0a344c55e5beef
- Info:
  - EXCEPTION (<class 'TypeError'>): BMVert.co
  -     C:\Users\JF\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\retopoflow\retopoflow\rfoperators\transform.py
  - 000 0345:translate() bmv.co = co
  - 001 0310:update() self.translate(context, event)
  -     C:\Users\JF\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\retopoflow\retopoflow\common\operator.py
  - 002 0143:modal() ret = self.update(context, event)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RFOperator.modal: Unhandled Exception Caught in self.update: BMVert.co
____________________________________________________________________________________________________
Exception Info
- Time: 2024-11-13 14:32:16.599833
- Count: 3
- Hash: 411c938379d6efc02f0a344c55e5beef
- Info:
  - EXCEPTION (<class 'TypeError'>): BMVert.co
  -     C:\Users\JF\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\retopoflow\retopoflow\rfoperators\transform.py
  - 000 0345:translate() bmv.co = co
  - 001 0310:update() self.translate(context, event)
  -     C:\Users\JF\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\retopoflow\retopoflow\common\operator.py
  - 002 0143:modal() ret = self.update(context, event)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Traceback (most recent call last):
  File "C:\Users\JF\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\retopoflow\retopoflow\rfcore.py", line 418, in modal
    RFCore.handle_update(context, event)
  File "C:\Users\JF\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\retopoflow\retopoflow\rfcore.py", line 234, in handle_update
    if brush: brush.update(context, event)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JF\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\retopoflow\retopoflow\rfbrushes\strokes_brush.py", line 171, in update
    self.operator.process_stroke(context, self.stroke, self.stroke_cycle, self.snap_bmv0, self.snap_bmv1)
  File "C:\Users\JF\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\retopoflow\retopoflow\rftool_strokes\strokes.py", line 114, in process_stroke
    logic = Strokes_Logic(context, stroke, cycle, snap_bmv0, snap_bmv1, self.span_insert_mode, self.initial_cut_count, RFTool_Strokes.rf_brush.radius)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JF\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\retopoflow\retopoflow\rftool_strokes\strokes_logic.py", line 118, in __init__
    self.length3D = sum((p1-p0).length for (p0,p1) in iter_pairs(self.stroke3D, self.is_cycle))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JF\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\retopoflow\retopoflow\rftool_strokes\strokes_logic.py", line 118, in <genexpr>
    self.length3D = sum((p1-p0).length for (p0,p1) in iter_pairs(self.stroke3D, self.is_cycle))
                         ~~^~~
TypeError: unsupported operand type(s) for -: 'NoneType' and 'NoneType'
```

&nbsp;

**How to Reproduce:**

- Just ctrl+click while using the stroke tool in edit mode.

**Comment by jfranmatheu** [comment]
## Issue 

After some superficial analysis, I've seen that `raycast_point_valid_sources` function can return `None` values, so in `Strokes_Logic.__init__()`, the `self.stroke3D` list can contain invalid values when there is no raycast hit, leading to a further crash.

## Potential bugfix:
- When can filter out the invalid projected points and fill a new list for 2d points but with the same filter pass so that we have both lists (2D and 3D) with same length and matching indices.

I made a quick patch in case you need to give it a try:
[1346.patch](https://github.com/user-attachments/files/17749946/1346.patch)

**Comment by vxlcoder** [comment]
thanks for the patch, @jfranmatheu!

It seems I ended up fixing this bug (differently than your patch) before I even noticed you reported the issue and had a fix.

this should be fixed now.

**Comment by jfranmatheu** [comment]
I confirm this works now, no crash anymore!
