### ISSUE TITLE
Freeze when continuing stroke off surface

### ISSUE THREAD

**Issue by jlampel** [CGCookie/retopoflow#1350]
Using strokes and drawing from a component to empty space causes RetopoFlow to freeze. 

![image](https://github.com/user-attachments/assets/053bb6bf-0e8e-4e18-b44e-76cf42a01203)

Here's the error:

```
Python: Traceback (most recent call last):
  File "C:\Users\Jonathan\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\retopoflow\retopoflow\rfcore.py", line 422, in modal
    RFCore.handle_update(context, event)
  File "C:\Users\Jonathan\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\retopoflow\retopoflow\rfcore.py", line 234, in handle_update
    if brush: brush.update(context, event)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jonathan\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\retopoflow\retopoflow\rfbrushes\strokes_brush.py", line 179, in update
    self.operator.process_stroke(context, self.stroke, self.stroke_cycle, self.snap_bmv0, self.snap_bmv1)
  File "C:\Users\Jonathan\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\retopoflow\retopoflow\rftool_strokes\strokes.py", line 116, in process_stroke
    logic = Strokes_Logic(context, stroke, cycle, snap_bmv0, snap_bmv1, self.span_insert_mode, self.initial_cut_count, RFTool_Strokes.rf_brush.radius)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jonathan\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\retopoflow\retopoflow\rftool_strokes\strokes_logic.py", line 227, in __init__
    self.length3D = sum((p1-p0).length for (p0,p1) in iter_pairs(self.stroke3D, self.is_cycle))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jonathan\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\retopoflow\retopoflow\rftool_strokes\strokes_logic.py", line 227, in <genexpr>
    self.length3D = sum((p1-p0).length for (p0,p1) in iter_pairs(self.stroke3D, self.is_cycle))
                         ~~^~~
AttributeError: Vector subtraction: (NoneType - Vector) invalid type for this operation
```

**Comment by jlampel** [comment]
This was fixed by 595cc4665790a4a384dc157187f47428a1ab19a2 !
