### ISSUE TITLE
Strokes: Error when focus jumps from Blender in the middle of a stroke

### ISSUE THREAD

**Issue by jlampel** [CGCookie/retopoflow#1381]
I doubt this would happen often, but I got this error when I set the Windows snipping tool to take a timed screenshot right in the middle of a stroke, which also makes the active window jump from Blender to the snipping tool. 

```
Python: Traceback (most recent call last):
  File "C:\Users\Jonathan\AppData\Roaming\Blender Foundation\Blender\4.3\scripts\addons\retopoflow\retopoflow\rfcore.py", line 449, in modal
    RFCore.handle_update(context, event)
  File "C:\Users\Jonathan\AppData\Roaming\Blender Foundation\Blender\4.3\scripts\addons\retopoflow\retopoflow\rfcore.py", line 247, in handle_update
    if brush: brush.update(context, event)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jonathan\AppData\Roaming\Blender Foundation\Blender\4.3\scripts\addons\retopoflow\retopoflow\rfbrushes\strokes_brush.py", line 182, in update
    self.operator.process_stroke(context, self.radius, self.stroke, self.stroke_cycle, self.snap_bmv0, self.snap_bmv1)
  File "C:\Users\Jonathan\AppData\Roaming\Blender Foundation\Blender\4.3\scripts\addons\retopoflow\retopoflow\rftool_strokes\strokes.py", line 220, in process_stroke
    RFOperator_Stroke_Insert.strokes_insert(context, radius, stroke3D, is_cycle, self.span_insert_mode, self.initial_cut_count, self.extrapolate_mode)
  File "C:\Users\Jonathan\AppData\Roaming\Blender Foundation\Blender\4.3\scripts\addons\retopoflow\retopoflow\rftool_strokes\strokes.py", line 122, in strokes_insert
    bpy.ops.retopoflow.strokes_insert('INVOKE_DEFAULT', True, extrapolate_mode=extrapolate_mode)
  File "C:\Program Files\Blender Foundation\Blender 4.3\4.3\scripts\modules\bpy\ops.py", line 107, in __call__
    ret = _op_call(self.idname_py(), kw, C_exec, C_undo)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Users\Jonathan\AppData\Roaming\Blender Foundation\Blender\4.3\scripts\addons\retopoflow\retopoflow\rftool_strokes\strokes.py", line 144, in execute
    self.cut_count = logic.cut_count
    ^^^^^^^^^^^^^^
  File "C:\Program Files\Blender Foundation\Blender 4.3\4.3\scripts\modules\bpy_types.py", line 946, in __setattr__
    return setattr(properties, attr, value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: bpy_struct: item.attr = val: RETOPOFLOW_OT_strokes_insert.cut_count expected an int type, not NoneType
Location: C:\Program Files\Blender Foundation\Blender 4.3\4.3\scripts\modules\bpy\ops.py:107
```

**Comment by vxlcoder** [comment]
i'm not able to reproduce this.  can you somehow capture a video?

**Comment by vxlcoder** [comment]
can you check to see if this still happens?  i might have fixed this, as I cannot reproduce this bug.

note: we can detect if Blender loses focus (`event.type=='WINDOW_DEACTIVATE'`), in which case we could halt stroking immediately, but i don't think that this would be expected behavior.

**Comment by jlampel** [comment]
I've tested this a bunch when creating gifs and I haven't seen an issue since!
