### ISSUE TITLE
Strokes: Error when drawing stroke in empty space

### ISSUE THREAD

**Issue by jlampel** [CGCookie/retopoflow#1388]
*I don't expect this to actually work* or produce useful results, but drawing a stroke from outside the mesh to the other side of the mesh, the exact same as if you were using contours, results in the following error:

```
RFCore_Operator executing
Traceback (most recent call last):
  File "C:\Users\Jonathan\AppData\Roaming\Blender Foundation\Blender\4.3\scripts\addons\retopoflow\retopoflow\rftool_strokes\strokes.py", line 183, in execute
    length3D = sum((p1-p0).length for (p0,p1) in iter_pairs(data['stroke3D'], data['is_cycle']))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jonathan\AppData\Roaming\Blender Foundation\Blender\4.3\scripts\addons\retopoflow\retopoflow\rftool_strokes\strokes.py", line 183, in <genexpr>
    length3D = sum((p1-p0).length for (p0,p1) in iter_pairs(data['stroke3D'], data['is_cycle']))
                    ~~^~~
AttributeError: Vector subtraction: (Vector - NoneType) invalid type for this operation
Error: Python: Traceback (most recent call last):
  File "C:\Users\Jonathan\AppData\Roaming\Blender Foundation\Blender\4.3\scripts\addons\retopoflow\retopoflow\rftool_strokes\strokes.py", line 183, in execute
    length3D = sum((p1-p0).length for (p0,p1) in iter_pairs(data['stroke3D'], data['is_cycle']))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jonathan\AppData\Roaming\Blender Foundation\Blender\4.3\scripts\addons\retopoflow\retopoflow\rftool_strokes\strokes.py", line 183, in <genexpr>
    length3D = sum((p1-p0).length for (p0,p1) in iter_pairs(data['stroke3D'], data['is_cycle']))
                    ~~^~~
AttributeError: Vector subtraction: (Vector - NoneType) invalid type for this operation
Location: C:\Program Files\Blender Foundation\Blender 4.3\4.3\scripts\modules\bpy\ops.py:107
Traceback (most recent call last):
  File "C:\Users\Jonathan\AppData\Roaming\Blender Foundation\Blender\4.3\scripts\addons\retopoflow\retopoflow\rfcore.py", line 458, in modal
    RFCore.handle_update(context, event)
  File "C:\Users\Jonathan\AppData\Roaming\Blender Foundation\Blender\4.3\scripts\addons\retopoflow\retopoflow\rfcore.py", line 250, in handle_update
    if brush: brush.update(context, event)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jonathan\AppData\Roaming\Blender Foundation\Blender\4.3\scripts\addons\retopoflow\retopoflow\rfbrushes\strokes_brush.py", line 197, in update
    self.operator.process_stroke(context, self.radius, self.stroke, self.stroke_cycle, self.snap_bmv0, self.snap_bmv1)
  File "C:\Users\Jonathan\AppData\Roaming\Blender Foundation\Blender\4.3\scripts\addons\retopoflow\retopoflow\rftool_strokes\strokes.py", line 332, in process_stroke
    RFOperator_Stroke_Insert.strokes_insert(
  File "C:\Users\Jonathan\AppData\Roaming\Blender Foundation\Blender\4.3\scripts\addons\retopoflow\retopoflow\rftool_strokes\strokes.py", line 153, in strokes_insert
    bpy.ops.retopoflow.strokes_insert('INVOKE_DEFAULT', True, extrapolate_mode=extrapolate_mode)
  File "C:\Program Files\Blender Foundation\Blender 4.3\4.3\scripts\modules\bpy\ops.py", line 107, in __call__
    ret = _op_call(self.idname_py(), kw, C_exec, C_undo)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by vxlcoder** [comment]
should be fixed!

**Comment by jlampel** [comment]
I no longer get this error when starting the stroke outside of the mesh, but I do get the error when starting on the mesh and drawing to the outside.

**Comment by vxlcoder** [comment]
ah, good catch.  fixed now!

**Comment by jlampel** [comment]
Confirmed fixed!
