### ISSUE TITLE
Tweak: brush not showing while navigating

### ISSUE THREAD

**Issue by carter2422** [CGCookie/retopoflow#140]
Getting this while navigating in Tweak right now:
```
Traceback (most recent call last):
  File "/Users/jonathanwilliamson/Dropbox (Personal)/blenderDev/addons/cgCookie/scripts/addons/retopoFlow/modaloperator.py", line 114, in draw_callback_postpixel
    self.draw_postpixel(context)
  File "/Users/jonathanwilliamson/Dropbox (Personal)/blenderDev/addons/cgCookie/scripts/addons/retopoFlow/op_tweak/tweak_modal.py", line 127, in draw_postpixel
    ray,hit = common_utilities.ray_cast_region2d(region, r3d, self.cur_pos, self.obj, settings)
AttributeError: 'module' object has no attribute 'ray_cast_region2d
```

**Comment by carter2422** [comment]
Confirmed fixed!
