### ISSUE TITLE
Crash when in edit mode for target when target not generated from previous RFlow operator

### ISSUE THREAD

**Issue by patmo141** [CGCookie/retopoflow#144]
clearing mesh cache
Traceback (most recent call last):
  File "/Users/jonathanwilliamson/Dropbox (Personal)/blenderDev/addons/cgCookie/scripts/addons/retopoFlow/modaloperator.py", line 240, in invoke
    self.modal_start(context)
  File "/Users/jonathanwilliamson/Dropbox (Personal)/blenderDev/addons/cgCookie/scripts/addons/retopoFlow/modaloperator.py", line 183, in modal_start
    self.start(context)
  File "/Users/jonathanwilliamson/Dropbox (Personal)/blenderDev/addons/cgCookie/scripts/addons/retopoFlow/op_polystrips/polystrips_modal.py", line 85, in start
    self.start_ui(context)
  File "/Users/jonathanwilliamson/Dropbox (Personal)/blenderDev/addons/cgCookie/scripts/addons/retopoFlow/op_polystrips/polystrips_ui.py", line 139, in start_ui
    bvh = BVHTree.FromBMesh(self.bme)
  File "/Users/jonathanwilliamson/blender-dev/blender-master/install/darwin/blender.app/Contents/MacOS/../Resources/2.75/scripts/modules/bpy_types.py", line 594, in __getattribute__
    return super().__getattribute__(attr)
AttributeError: 'CGC_Polystrips' object has no attribute 'bme'

location: <unknown location>:-1

location: <unknown location>:-1
Traceback (most recent call last):
  File "/Users/jonathanwilliamson/Dropbox (Personal)/blenderDev/addons/cgCookie/scripts/addons/retopoFlow/modaloperator.py", line 109, in draw_callback_postview
    self.draw_postview(context)
  File "/Users/jonathanwilliamson/blender-dev/blender-master/install/darwin/blender.app/Contents/MacOS/../Resources/2.75/scripts/modules/bpy_types.py", line 590, in __getattribute__
    properties = StructRNA.path_resolve(self, "properties")
ReferenceError: StructRNA of type CGC_Polystrips has been removed
Traceback (most recent call last):
  File "/Users/jonathanwilliamson/Dropbox (Personal)/blenderDev/addons/cgCookie/scripts/addons/retopoFlow/modaloperator.py", line 114, in draw_callback_postpixel
    self.draw_postpixel(context)
  File "/Users/jonathanwilliamson/blender-dev/blender-master/install/darwin/blender.app/Contents/MacOS/../Resources/2.75/scripts/modules/bpy_types.py", line 590, in __getattribute__
    properties = StructRNA.path_resolve(self, "properties")
ReferenceError: StructRNA of type CGC_Polystrips has been removed
Traceback (most recent call last):
  File "/Users/jonathanwilliamson/Dropbox (Personal)/blenderDev/addons/cgCookie/scripts/addons/retopoFlow/modaloperator.py", line 203, in modal
    eventd = self.get_event_details(context, event)
  File "/Users/jonathanwilliamson/blender-dev/blender-master/install/darwin/blender.app/Contents/MacOS/../Resources/2.75/scripts/modules/bpy_types.py", line 590, in __getattribute__
    properties = StructRNA.path_resolve(self, "properties")
ReferenceError: StructRNA of type CGC_Polystrips has been removed

**Comment by patmo141** [comment]
typo caused this in BVH generation in PS startup.
