### ISSUE TITLE
Polystraps - Tweak Traceback

### ISSUE THREAD

**Issue by Denson01** [CGCookie/retopoflow#181]
Each time i try to Tweak anything i get this Tracebacks
```
Traceback (most recent call last):
  File "D:\Gry\Steam\steamapps\common\Blender\2.76\scripts\addons\retopoflow-master\modaloperator.py", line 244, in modal
    nmode = self.FSM[self.fsm_mode](context, eventd)
  File "D:\Gry\Steam\steamapps\common\Blender\2.76\scripts\addons\retopoflow-master\op_polystrips\polystrips_ui_tools.py", line 241, in modal_tweak_move_tool
    self.modal_tweak_setup(context, eventd)
  File "D:\Gry\Steam\steamapps\common\Blender\2.76\scripts\addons\retopoflow-master\op_polystrips\polystrips_ui_tools.py", line 193, in modal_tweak_setup
    if not ge.is_fromMesh():
AttributeError: 'GEdge' object has no attribute 'is_fromMesh'

location: <unknown location>:-1

Traceback (most recent call last):
  File "D:\Gry\Steam\steamapps\common\Blender\2.76\scripts\addons\retopoflow-master\modaloperator.py", line 244, in modal
    nmode = self.FSM[self.fsm_mode](context, eventd)
  File "D:\Gry\Steam\steamapps\common\Blender\2.76\scripts\addons\retopoflow-master\op_polystrips\polystrips_ui_tools.py", line 241, in modal_tweak_move_tool
    self.modal_tweak_setup(context, eventd)
  File "D:\Gry\Steam\steamapps\common\Blender\2.76\scripts\addons\retopoflow-master\op_polystrips\polystrips_ui_tools.py", line 168, in modal_tweak_setup
    lallverts += [c for gv,_,c,_ in l if not gv.is_fromMesh()]
  File "D:\Gry\Steam\steamapps\common\Blender\2.76\scripts\addons\retopoflow-master\op_polystrips\polystrips_ui_tools.py", line 168, in <listcomp>
    lallverts += [c for gv,_,c,_ in l if not gv.is_fromMesh()]
AttributeError: 'GVert' object has no attribute 'is_fromMesh'

location: <unknown location>:-1
```

**Comment by carter2422** [comment]
Thanks for the report @Denson01. I'll look into it.

**Comment by carter2422** [comment]
@Denson01 are you able to consistently reproduce this?

**Comment by carter2422** [comment]
Never mind, I see. This is a bad bug that shouldn't have slipped through, sorry about that. 

@Denson01 for the time being you can use Tweak in Edit Mode as it's own tool.

**Comment by Denson01** [comment]
No problem :)

Yeah in Edit Mode it works just fine.

**Comment by carter2422** [comment]
@Denson01 bugfix release imminent.

**Comment by Denson01** [comment]
<3 already tested, works PERFECT :)
