### ISSUE TITLE
Error After Installing/Missing Interface Buttons

### ISSUE THREAD

**Issue by directorsaint** [CGCookie/retopoflow#183]
![screen shot 2015-12-15 at 8 24 36 pm](https://cloud.githubusercontent.com/assets/16314017/11829448/afbebbd6-a36a-11e5-9878-e36ba25f4b98.JPG)
![screen shot 2015-12-15 at 8 24 29 pm](https://cloud.githubusercontent.com/assets/16314017/11829452/b3632d12-a36a-11e5-929c-bbe66532f5da.JPG)

**Comment by carter2422** [comment]
@directorsaint I'm guessing you're not using English as the system language in Blender? Unfortunately this will break things for now until we improve the internalization of it.

**Comment by directorsaint** [comment]
Hmmm...everything seems to be in English. Where would the setting be to make sure?

**Comment by carter2422** [comment]
Have anything set here? http://cl.ly/e5sV

**Comment by directorsaint** [comment]
![screen shot 2015-12-15 at 9 06 15 pm](https://cloud.githubusercontent.com/assets/16314017/11830093/dc5c9a14-a36f-11e5-80b9-06fab485727b.JPG)
This is what is configured there on my side.

**Comment by carter2422** [comment]
Just to be sure, have you restarted Blender and then tried enabling it?

Also, are you using the daily build of Blender or official 2.76 release?

**Comment by directorsaint** [comment]
Did the above with the same results. It is the last official build from blender.org 2.76. The problem isn't that it won't enable, it just has the missing interface buttons and throws the errors when i click on any of the buttons on Retopoflows' interface

**Comment by carter2422** [comment]
Okay here's something to try. 

Are you familiar with how to start Blender from a terminal? If so, do that and then see if any errors are outputted to the terminal when you click on the Retopology panel in the toolbar. Or upon activating the add-on.

**Comment by directorsaint** [comment]
![screen shot 2015-12-15 at 9 29 10 pm](https://cloud.githubusercontent.com/assets/16314017/11830440/39073b7c-a373-11e5-8628-810863622260.JPG)

**Comment by carter2422** [comment]
Huh...this is going to take some research to figure out. Blender is internationalizing the variable for some reason, causing the name to change from `settings` to `UI_AP_i18n_settings`.

**Comment by directorsaint** [comment]
localhost:~ santelmovazquez$ /Applications/Blender-Builds/blender-2.76/blender.app 
-bash: /Applications/Blender-Builds/blender-2.76/blender.app: is a directory
localhost:~ santelmovazquez$ /Applications/Blender-Builds/blender-2.76/blender.app/Contents/MacOS/blender 
ndof: 3Dx driver not found
Read new prefs: /Users/santelmovazquez/Library/Application Support/Blender/2.76/config/userpref.blend
found bundled python: /Applications/Blender-Builds/blender-2.76/blender.app/Contents/MacOS/../Resources/2.76/python
Loaded Animation Nodes with 149 modules
create isosurfer handlers...
isosurfer handler created successfully!
measureit: added to phytonpath
measureit: Imported multifiles
/Applications/Blender-Builds/blender-2.76/blender.app/Contents/Resources/2.76/python/lib/python3.4/importlib/_bootstrap.py:321: RuntimeWarning: compiletime version 3.3 of module 'cmolcore' does not match runtime version 3.4
  return f(*args, **kwds)
cmolcore imported with sucess! v0.04
Imported multifiles
addon not found: 'fracture_helper'
------------------------------
Traceback (most recent call last):
  File "/Users/santelmovazquez/Library/Application Support/Blender/2.76/scripts/addons/retopoFlow/lib/common_utilities.py", line 85, in check_source_target_objects
    if settings.source_object not in bpy.context.scene.objects:
AttributeError: 'NoneType' object has no attribute 'source_object'
Traceback (most recent call last):
  File "/Users/santelmovazquez/Library/Application Support/Blender/2.76/scripts/addons/retopoFlow/lib/common_utilities.py", line 83, in check_source_target_objects
    settings = get_settings()
  File "/Users/santelmovazquez/Library/Application Support/Blender/2.76/scripts/addons/retopoFlow/lib/common_utilities.py", line 76, in get_settings
    assert False, 'could not find non-"lib" folder'
AssertionError: could not find non-"lib" folder
Traceback (most recent call last):
  File "/Users/santelmovazquez/Library/Application Support/Blender/2.76/scripts/addons/retopoFlow/lib/common_utilities.py", line 85, in check_source_target_objects
    if settings.source_object not in bpy.context.scene.objects:
AttributeError: 'NoneType' object has no attribute 'source_object'
Traceback (most recent call last):
  File "/Users/santelmovazquez/Library/Application Support/Blender/2.76/scripts/addons/retopoFlow/lib/common_utilities.py", line 85, in check_source_target_objects
    if settings.source_object not in bpy.context.scene.objects:
AttributeError: 'UI_AP_i18n_settings' object has no attribute 'source_object'
Traceback (most recent call last):
  File "/Users/santelmovazquez/Library/Application Support/Blender/2.76/scripts/addons/retopoFlow/lib/common_utilities.py", line 85, in check_source_target_objects
    if settings.source_object not in bpy.context.scene.objects:
AttributeError: 'UI_AP_i18n_settings' object has no attribute 'source_object'
Traceback (most recent call last):
  File "/Users/santelmovazquez/Library/Application Support/Blender/2.76/scripts/addons/retopoFlow/lib/common_utilities.py", line 85, in check_source_target_objects
    if settings.source_object not in bpy.context.scene.objects:
AttributeError: 'UI_AP_i18n_settings' object has no attribute 'source_object'
Traceback (most recent call last):
  File "/Users/santelmovazquez/Library/Application Support/Blender/2.76/scripts/addons/retopoFlow/lib/common_utilities.py", line 85, in check_source_target_objects
    if settings.source_object not in bpy.context.scene.objects:
AttributeError: 'UI_AP_i18n_settings' object has no attribute 'source_object'
Traceback (most recent call last):
  File "/Users/santelmovazquez/Library/Application Support/Blender/2.76/scripts/addons/retopoFlow/lib/common_utilities.py", line 85, in check_source_target_objects
    if settings.source_object not in bpy.context.scene.objects:
AttributeError: 'UI_AP_i18n_settings' object has no attribute 'source_object'
Traceback (most recent call last):
  File "/Users/santelmovazquez/Library/Application Support/Blender/2.76/scripts/addons/retopoFlow/lib/common_utilities.py", line 85, in check_source_target_objects
    if settings.source_object not in bpy.context.scene.objects:
AttributeError: 'UI_AP_i18n_settings' object has no attribute 'source_object'
Traceback (most recent call last):
  File "/Users/santelmovazquez/Library/Application Support/Blender/2.76/scripts/addons/retopoFlow/lib/common_utilities.py", line 85, in check_source_target_objects
    if settings.source_object not in bpy.context.scene.objects:
AttributeError: 'UI_AP_i18n_settings' object has no attribute 'source_object'
Traceback (most recent call last):
  File "/Users/santelmovazquez/Library/Application Support/Blender/2.76/scripts/addons/retopoFlow/lib/common_utilities.py", line 85, in check_source_target_objects
    if settings.source_object not in bpy.context.scene

**Comment by directorsaint** [comment]
Appreciate it. No rush for now I will use 1.1.1 as it seems to work ok for now. Let me know if you can figure out what's going on. Thank You

**Comment by MysticGems** [comment]
For what it's worth, reproduces for me as well: OS X 10.11.2, Blender 2.76b, hash f337fea.

**Comment by directorsaint** [comment]
Maybe an OSX issue?

**Comment by carter2422** [comment]
@patmo141, @vxlcoder going to need some help tracking this one down. Might need to inquire with Blender devs.

**Comment by carter2422** [comment]
@directorsaint, @MysticGems can you two give this branch a try to see if it's fixed? https://github.com/CGCookie/retopoflow/tree/issue/183

**Comment by directorsaint** [comment]
Seems to work now...except there is a "missing script files" not sure if that affects anything.
![screen shot 2015-12-30 at 2 50 50 am](https://cloud.githubusercontent.com/assets/16314017/12047862/9faff192-aea0-11e5-9eb1-c8d949ee56b0.JPG)
![screen shot 2015-12-30 at 2 51 16 am](https://cloud.githubusercontent.com/assets/16314017/12047864/a5a73fba-aea0-11e5-9dc4-d7aec5f6130b.JPG)

**Comment by vxlcoder** [comment]
@directorsaint it looks like the other retopoflow is from a previous install or something similar to that.  you should be able to uncheck it, then save your prefs, and it will not show anymore.

**Comment by carter2422** [comment]
When installing new versions it's best to completely remove the previous one first since Blender does not have any kind of add-on updater.

**Comment by directorsaint** [comment]
Ah Ok! Thanks all for the help!
