### ISSUE TITLE
Undoing a Thaw and then selecting a strip causes a crash

### ISSUE THREAD

**Issue by carter2422** [CGCookie/retopoflow#190]
Undoing a Thaw and then selecting a strip will immediate crash polystrips: 
```
Traceback (most recent call last):
  File "/Users/jonathanwilliamson/Dropbox (Personal)/blenderDev/addons/cgCookie/scripts/addons/retopoFlow/modaloperator.py", line 244, in modal
    nmode = self.FSM[self.fsm_mode](context, eventd)
  File "/Users/jonathanwilliamson/Dropbox (Personal)/blenderDev/addons/cgCookie/scripts/addons/retopoFlow/modaloperator.py", line 198, in modal_main
    nmode = self.FSM['wait'](context, eventd)
  File "/Users/jonathanwilliamson/Dropbox (Personal)/blenderDev/addons/cgCookie/scripts/addons/retopoFlow/op_polystrips/polystrips_ui_modalwait.py", line 108, in modal_wait
    self.create_undo_snapshot('sketch')
  File "/Users/jonathanwilliamson/Dropbox (Personal)/blenderDev/addons/cgCookie/scripts/addons/retopoFlow/op_polystrips/polystrips_ui.py", line 228, in create_undo_snapshot
    act_gedge = self.polystrips.gedges.index(self.act_gedge)
ValueError: <retopoFlow.op_polystrips.polystrips_datastructure.GEdge object at 0x11f825d68> is not in list
```

**Comment by vxlcoder** [comment]
This bug seems to be fixed already, although it is from many months ago.  the touched file has only a few lines changed, so merging should not be difficult.  let me know if the changes do not fix the issue.
