### ISSUE TITLE
ReferenceError: StructRNA of type CGC_Contours has been removed

### ISSUE THREAD

**Issue by carter2422** [CGCookie/retopoflow#241]
We've had this error for a longtime and never been able to track it down. I probably get it 100s or 1000s of times per session. It doesn't seem to actually cause any problems but it absolutely floods the console. 

```
Traceback (most recent call last):
  File "/Users/jonathanwilliamson/Dropbox (Personal)/blenderDev/addons/cgCookie/scripts/addons/retopoflow/modaloperator.py", line 171, in draw_callback_postpixel
    self.handle_exception()
  File "/Users/jonathanwilliamson/blender-dev/blender-master/build_darwin/bin/blender.app/Contents/MacOS/./../Resources/2.77/scripts/modules/bpy_types.py", line 590, in __getattribute__
    properties = StructRNA.path_resolve(self, "properties")
ReferenceError: StructRNA of type CGC_Contours has been removed
```

**Comment by carter2422** [comment]
This might actually be one for you @vxlcoder since it deals with the modal operator and exception handling.

**Comment by vxlcoder** [comment]
@carter2422 could this be at all related to having two versions of retopoflow installed?

**Comment by carter2422** [comment]
I think you're right @vxlcoder. I cannot replicate this now.
