### ISSUE TITLE
Various tool errors and crashes when reopened after closing with several patches incomplete

### ISSUE THREAD

**Issue by briligg** [CGCookie/retopoflow#269]
Polypen and Polystrips quickly produce errors, Polypen produced one asking me to report it, so i am. 

Part of error message: 

Traceback (most recent call last):
  File "/home/briligg/.config/blender/2.77/scripts/addons/retopoFlow/modaloperator.py", line 163, in draw_callback_postview
    self.handle_exception()
  File "/home/briligg/blender-2.77a-linux-glibc211-x86_64/2.77/scripts/modules/bpy_types.py", line 593, in **getattribute**
    properties = StructRNA.path_resolve(self, "properties")
ReferenceError: StructRNA of type CGC_Polystrips has been removed
Traceback (most recent call last):
  File "/home/briligg/.config/blender/2.77/scripts/addons/retopoFlow/modaloperator.py", line 169, in draw_callback_postpixel
    self.draw_postpixel(context)
  File "/home/briligg/blender-2.77a-linux-glibc211-x86_64/2.77/scripts/modules/bpy_types.py", line 593, in **getattribute**
    properties = StructRNA.path_resolve(self, "properties")
ReferenceError: StructRNA of type CGC_Polystrips has been removed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/briligg/.config/blender/2.77/scripts/addons/retopoFlow/modaloperator.py", line 171, in draw_callback_postpixel
    self.handle_exception()
  File "/home/briligg/blender-2.77a-linux-glibc211-x86_64/2.77/scripts/modules/bpy_types.py", line 593, in **getattribute**
    properties = StructRNA.path_resolve(self, "properties")
ReferenceError: StructRNA of type CGC_Polystrips has been removed

[Retopo-Lalande-CGCookie.blend.zip](https://github.com/CGCookie/retopoflow/files/516415/Retopo-Lalande-CGCookie.blend.zip)

**Comment by briligg** [comment]
PS - I realize i'm trying to make Retopoflow do something it wasn't designed to do. I have only a rough topographic map of the crater on the Moon i'm recreating, so i'm getting the retopology to stick to that map, while making the quads follow the much higher resolution images of that crater. Once i have that, i can edit them to get something much more detailed and accurate.

So, Retopoflow maybe is affected by that, and maybe the fact that i closed the file while there were still a bunch of unfinished patches was problematic too. A backup from a couple of hours before also had problems, and i've started over.

**Comment by vxlcoder** [comment]
I believe this issue applies to v1.x only, so I'm going to close this issue now that v2.0 is officially released (see `release/2.0.0` branch or Blender Market page).  If this is still an issue with v2.0, please reopen, and post more details.  Thanks for reporting this issue, and we look forward to seeing how v2.0 helps your retopo workflow!
