### ISSUE TITLE
Tweak: adjusting segments in gedge adjacent to tweaked patch makes everything disappear momentarily

### ISSUE THREAD

**Issue by carter2422** [CGCookie/retopoflow#37]
If you tweak a patch and then try and adjust the segments of an adjacent gedge it breaks. Everything but the tweaked patch disappears.

Console output:

``````
Traceback (most recent call last):
  File "/Users/jonathanwilliamson/Dropbox (Personal)/blenderDev/addons/cgCookie/scripts/addons/retopoFlow/__init__.py", line 2214, in draw_callback
    return self.ui.draw_callback(context)
  File "/Users/jonathanwilliamson/Dropbox (Personal)/blenderDev/addons/cgCookie/scripts/addons/retopoFlow/__init__.py", line 2505, in draw_callback
    self.draw_callback_themed(context)
  File "/Users/jonathanwilliamson/Dropbox (Personal)/blenderDev/addons/cgCookie/scripts/addons/retopoFlow/__init__.py", line 2550, in draw_callback_themed
    for (p0,p1,p2,p3) in gpatch.iter_segments(only_visible=True):
  File "/Users/jonathanwilliamson/Dropbox (Personal)/blenderDev/addons/cgCookie/scripts/addons/retopoFlow/polystrips.py", line 1296, in iter_segments
    if not all(self.visible[idx] for idx in lidxs):
  File "/Users/jonathanwilliamson/Dropbox (Personal)/blenderDev/addons/cgCookie/scripts/addons/retopoFlow/polystrips.py", line 1296, in <genexpr>
    if not all(self.visible[idx] for idx in lidxs):
KeyError: (11, 1)```

![screen shot 2015-01-03 at 10 28 39 pm](https://cloud.githubusercontent.com/assets/1648631/5604776/f6086094-9397-11e4-92e6-fb3b9bb5724c.png)
![screen shot 2015-01-03 at 10 29 26 pm](https://cloud.githubusercontent.com/assets/1648631/5604777/fd6338aa-9397-11e4-8952-9c873d9e1fac.png)
``````

**Note:** the behavior is slightly different when increasing/decreasing segments.

**Comment by carter2422** [comment]
This is no longer an issue due to changes in how patch cascading is handled.
