### ISSUE TITLE
Polystrips fails on start if "BezierCurve" object exists

### ISSUE THREAD

**Issue by carter2422** [CGCookie/retopoflow#4]
If a bezier curve object with name "BezierCurve" is present in scene upon starting Polystrips then it fails.

```
Traceback (most recent call last):
  File "/Users/jonathanwilliamson/Dropbox (Personal)/blenderDev/addons/cgCookie/scripts/addons/retopoFlow/__init__.py", line 2200, in invoke
    self.ui = PolystripsUI(context, event)
  File "/Users/jonathanwilliamson/Dropbox (Personal)/blenderDev/addons/cgCookie/scripts/addons/retopoFlow/__init__.py", line 2348, in __init__
    self.create_polystrips_from_bezier(bpy.data.objects['BezierCurve'])
  File "/Users/jonathanwilliamson/Dropbox (Personal)/blenderDev/addons/cgCookie/scripts/addons/retopoFlow/__init__.py", line 3678, in create_polystrips_from_bezier
    gv0 = pregv if pregv else self.create_gvert(mx, bp0.co, 0.2)
AttributeError: 'PolystripsUI' object has no attribute 'create_gvert'
```

**Comment by carter2422** [comment]
I can no longer repo this. Not sure when it was fixed but closing out.
