### ISSUE TITLE
Invalid Syntax

### ISSUE THREAD

**Issue by notfood** [CGCookie/retopoflow#590]
```stacktrace
Traceback (most recent call last):
  File "/usr/share/blender/2.79/scripts/modules/addon_utils.py", line 331, in enable
    mod = __import__(module_name)
  File "/media/Makai/home/.config/blender/2.79/scripts/addons/retopoflow/__init__.py", line 69, in <module>
    raise e
  File "/media/Makai/home/.config/blender/2.79/scripts/addons/retopoflow/__init__.py", line 48, in <module>
    from .interface import (
  File "/media/Makai/home/.config/blender/2.79/scripts/addons/retopoflow/interface.py", line 40, in <module>
    from .rfmode.rftool import RFTool
  File "/media/Makai/home/.config/blender/2.79/scripts/addons/retopoflow/rfmode/rftool.py", line 36, in <module>
    from .rfwidget import RFWidget_Default
  File "/media/Makai/home/.config/blender/2.79/scripts/addons/retopoflow/rfmode/rfwidget.py", line 29, in <module>
    from ..common.ui import Drawing
  File "/media/Makai/home/.config/blender/2.79/scripts/addons/retopoflow/common/ui.py", line 1373
    def __init__(self, image_data, margin=0, async=True, width=None, height=None):
                                                 ^
SyntaxError: invalid syntax
```

I can't enable the addon because I get invalid syntax. 

-edit-

Additional details:
Running ArchLinux 4.17.13-arch1-1-ARCH
Blender 2.79b
Python 3.7.0

-edit-

seems it doesn't like the word async

**Comment by notfood** [comment]
Renaming the async word to Async fixes the issue.

**Comment by vxlcoder** [comment]
good catch, @notfood!  I've made the change (using `async_load` instead of `async`) to correct this.
Thanks!

**Comment by notfood** [comment]
Works fine, found no other issues.

**Comment by vxlcoder** [comment]
Great!  closing.
