### ISSUE TITLE
Cannot extend from existing geometry, into clip, if the existing geo is on clip plane

### ISSUE THREAD

**Issue by carter2422** [CGCookie/retopoflow#61]
```
Traceback (most recent call last):
  File "/Users/jonathanwilliamson/Dropbox (Personal)/blenderDev/addons/cgCookie/scripts/addons/retopoFlow/__init__.py", line 2180, in modal
    ret = self.ui.modal(context, event)
  File "/Users/jonathanwilliamson/Dropbox (Personal)/blenderDev/addons/cgCookie/scripts/addons/retopoFlow/__init__.py", line 4044, in modal
    nmode = FSM[self.mode](eventd)
  File "/Users/jonathanwilliamson/Dropbox (Personal)/blenderDev/addons/cgCookie/scripts/addons/retopoFlow/__init__.py", line 3705, in modal_sketching
    self.polystrips.insert_gedge_from_stroke(p3d[:next_i_p], False)
  File "/Users/jonathanwilliamson/Dropbox (Personal)/blenderDev/addons/cgCookie/scripts/addons/retopoFlow/polystrips.py", line 1752, in insert_gedge_from_stroke
    self.extension_geometry.remove(gv3[0])
ValueError: list.remove(x): x not in list
```

![screen shot 2015-01-05 at 12 48 05 pm](https://cloud.githubusercontent.com/assets/1648631/5617911/1f10f5d6-94d9-11e4-8118-423159349ede.png)

**Possible Solution**: if attempting to extend into the clipped side, from the clip plane, report error to the user.

**Comment by vxlcoder** [comment]
@carter2422, I'm a little confused by clip and clip plane.  can you give some more details?

**Comment by carter2422** [comment]
Actually I don't think this is valid anymore. When geo is on the negative side of the clip plane then you shouldn't be able to manipulate it anyway, since symmetry is intended to be one-directional....marking as invalid for now and closing.
