### ISSUE TITLE
[BUG] - Issue enable add-on Blender 2.81

### ISSUE THREAD

**Issue by Rheyk** [CGCookie/retopoflow#779]
**Retopoflow Version:** {3.00 alpha}

**Blender Version (Hash):** {2.81}

**Platform:** {Windows}

**Issue:**

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.81\2.81\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\kreignier\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\retopoflow-b280\__init__.py", line 38, in <module>
    from .retopoflow import retopoflow
  File "C:\Users\kreignier\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\retopoflow-b280\retopoflow\retopoflow.py", line 25, in <module>
    from .rf.rf_blender     import RetopoFlow_Blender
  File "C:\Users\kreignier\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\retopoflow-b280\retopoflow\rf\rf_blender.py", line 30, in <module>
    from ...config.options import options, retopoflow_version
  File "C:\Users\kreignier\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\retopoflow-b280\config\options.py", line 33, in <module>
    from ..addon_common.common.blender import get_preferences
ModuleNotFoundError: No module named 'retopoflow-b280.addon_common.common'

**Comment by Rheyk** [comment]
Didn't see the instructions on the readme file! Sorry :(.

It worked

**Comment by mallerius** [comment]
Hey, I'm having the same issue but i can't find the instructions you mentioned. Could you help me out?

**Comment by Rheyk** [comment]
Hi,

I found an existing thread that solve this issue : https://github.com/CGCookie/retopoflow/issues/746

**Comment by mallerius** [comment]
wow thanks for the fast answere!

**Comment by vxlcoder** [comment]
Sorry that I didn't get to this sooner.

Thanks for answering @Rheyk!

Closing for now, but let us know if you have any other problems.  Thanks!
