### ISSUE TITLE
[BUG] Can't activate the addon (3.0.0 beta) on Blender 2.82 Official

### ISSUE THREAD

**Issue by xan2622** [CGCookie/retopoflow#797]
Hi.

I am not sure if the issue is similar to https://github.com/CGCookie/retopoflow/issues/772 but I thought you'd prefer I open a new Issue Report.

---
Retopoflow Version: **3.0.0 beta - Latest commit: 797202a**
Blender Version/Hash: **2.82 Official**
Platform Version/Distribution: **Windows 64 bits**

**Issue:**

I have tried to install the addon on Blender 2.82 official (windows 64 bits).
I have tried twice: 
- after downloading the source code from the main 280 branch: 
https://github.com/CGCookie/retopoflow/tree/b280
- from the Releases page: 
https://github.com/CGCookie/retopoflow/releases/tag/v3.0.0-beta-1

I've been told to extract the content of this repository: https://github.com/CGCookie/addon_common inside the ` addon_common ` folder, that's what I did.

But when I try to activate the addon, here is the error that I get:

> Traceback (most recent call last):
  File "E:\DONNES_SEB\APPS\IMAGE_AUDIO\Logiciels 3D\0_blender\blender_official\2.82\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\Sebastien\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\retopoflow\__init__.py", line 38, in <module>
    from .retopoflow import retopoflow
  File "C:\Users\Sebastien\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\retopoflow\retopoflow\retopoflow.py", line 25, in <module>
    from .rf.rf_blender     import RetopoFlow_Blender
  File "C:\Users\Sebastien\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\retopoflow\retopoflow\rf\rf_blender.py", line 30, in <module>
    from ...config.options import options, retopoflow_version
  File "C:\Users\Sebastien\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\retopoflow\config\options.py", line 33, in <module>
    from ..addon_common.common.blender import get_preferences
ImportError: cannot import name 'get_preferences' from 'retopoflow.addon_common.common.blender' (C:\Users\Sebastien\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\retopoflow\addon_common\common\blender.py)

Restarting Blender didn't solve the issue.

**Comment by xan2622** [comment]
I've been advised to follow this step by step installation tutorial: 
https://www.reddit.com/r/blenderhelp/comments/eljxj8/short_guide_on_getting_retopoflow_30_to_work_from/

It now works 👍  (I have been able to activate **Retopoflow 3.0.0 Beta** on Blender 2.82 without any error).

---

IMO, it would be useful to add this installation process on https://github.com/CGCookie/retopoflow/blob/master/README.md

**Comment by jlampel** [comment]
Thanks for letting us know! Agreed 👍
