### ISSUE TITLE
[BUG] RF no longer shows/starts after updating from v3.00.0

### ISSUE THREAD

**Issue by benjaminghys** [CGCookie/retopoflow#802]
Retopoflow Version: 3.00.0 beta
Blender Version 2.82a
Platform Version/Distribution: Windows 10 - 64 bit

When using the updater and restarting blender the RF button is gone.
Disabling and re-enabling the add-on spams out an error message.

![image](https://user-images.githubusercontent.com/23158001/78796346-76a8bc80-79b6-11ea-814d-d7bee7fc80cc.png)

- Installing the add-on from zip folder.
- Update RF from the dropdown list & restart blender.
- After restarting the RF button is nowhere to be seen anymore.
- Open preferences > add ons, disable RF & then enable RF again
(throws out following error in preferences window)

> Traceback (most recent call last):
  File "E:\Program Files(x86)\Blender\2.82\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\benja\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\RetopoFlow\__init__.py", line 38, in <module>
    from .retopoflow import retopoflow
  File "C:\Users\benja\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\RetopoFlow\retopoflow\retopoflow.py", line 25, in <module>
    from .rf.rf_blender     import RetopoFlow_Blender
  File "C:\Users\benja\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\RetopoFlow\retopoflow\rf\rf_blender.py", line 30, in <module>
    from ...config.options import options, retopoflow_version
  File "C:\Users\benja\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\RetopoFlow\config\options.py", line 33, in <module>
    from ..addon_common.common.blender import get_preferences
  File "C:\Users\benja\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\RetopoFlow\addon_common\common\__init__.py", line 38, in <module>
    from .retopoflow import retopoflow
  File "C:\Users\benja\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\RetopoFlow\addon_common\common\retopoflow\retopoflow.py", line 25, in <module>
    from .rf.rf_blender     import RetopoFlow_Blender
  File "C:\Users\benja\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\RetopoFlow\addon_common\common\retopoflow\rf\rf_blender.py", line 30, in <module>
    from ...config.options import options, retopoflow_version
  File "C:\Users\benja\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\RetopoFlow\addon_common\common\config\options.py", line 33, in <module>
    from ..addon_common.common.blender import get_preferences
ModuleNotFoundError: No module named 'RetopoFlow.addon_common.common.addon_common.common'
<

Removing the add-on and re-installing from zip makes it work again.

**Comment by vxlcoder** [comment]
Thanks for the report!  I do believe the updater is broken, unfortunately.  This is on my to-do list :)

**Comment by ArcLightPictures** [comment]
Replicatable....Yes the same issue on my side using the updater.

**Comment by jlampel** [comment]
The updater has been fixed!
